name: RSSible

services:
  rssible:
    build: .
    container_name: rssible-scraper
    volumes:
      # Mount feeds directory to persist generated XML files
      - ./feeds:/app/feeds
      # Mount source code for development (optional)
      - ./rssible:/app/rssible
    environment:
      - PYTHONPATH=/app
      - SCRAPY_SETTINGS_MODULE=rssible.settings
    # Override default command - you can specify which spider to run
    # command: scrapy crawl hackernews
